//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Commons
{
    [DataContract]
    public partial class Proveedor
    {
        #region Primitive Properties
    [DataMember]
    [Required]
        public virtual int Id
        {
            get;
            set;
        }
    [DataMember]
    [Required]
        public virtual string Nombre
        {
            get;
            set;
        }
    [DataMember]
    [Required]
        public virtual long Telefono
        {
            get;
            set;
        }
    [DataMember]
    [Required]
        public virtual decimal Deuda
        {
            get;
            set;
        }

        #endregion

    }
}
